### ISSUE TITLE
Прокликиватель ozon починить

### ISSUE THREAD

**Issue by pelid** [LevelUp-developers/Icebox#12]
Evgeny Evseev, [07.12.16 11:54]
ozon снова отвалился - http://partners.bpt.levelupdev.ru:8050/

Иван Ельчин, [07.12.16 11:54]
Это они интерфейс корзины переделали
Я прокликал руками - работает

Evgeny Evseev, [07.12.16 11:55]
видимо, как нагрузка спадет - после НГ - будем чинить
занес себе в таск трекер чтобы вспомнить

**Comment by sergunich** [comment]
Sergey Anuchin, [07.12.16 12:18]
ozon починился, это был единичный сбой из-за того что у них сайт подтормаживает
